name: Deploy

on:
  push:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: deploy
      run: |
         ssh -i "fastapi_key.pem" ubuntu@ec2-13-60-92-192.eu-north-1.compute.amazonaws.com
          cd fastapi-book-project
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          sudo systemctl restart nginx
          python3 -m uvicorn main:app
